version: "2.2"

services:
  resolver:
    build:
      context: ./resolver
      dockerfile: Dockerfile
    networks:
      local_network:
        ipv4_address: 192.168.0.5
    container_name: resolv

  soa_interne:
    build:
      context: ./soa_interne
      dockerfile: Dockerfile
    networks:
      local_network:
        ipv4_address: 192.168.0.1
    container_name: soa

  intranet:
    build:
      context: ./intranet
      dockerfile: Dockerfile
    networks:
      local_network:
        ipv4_address: 192.168.0.3
    ports:
      - "8080:80"
    container_name: intranet

  samba:
    build:
      context: ./samba
      dockerfile: Dockerfile
    networks:
      local_network:
        ipv4_address: 192.168.0.4
    ports:
      - "139:139"
    container_name: samba_container

  secretariat:
    build:
      context: ./user/secretariat
      dockerfile: Dockerfile
    networks:
      local_network:
        ipv4_address: 192.168.0.101
    container_name: secretariat

  compta:
    build:
      context: ./user/compta
      dockerfile: Dockerfile
    networks:
      local_network:
        ipv4_address: 192.168.0.102
    container_name: compta

  direction:
    build:
      context: ./user/direction
      dockerfile: Dockerfile
    networks:
      local_network:
        ipv4_address: 192.168.0.103
    container_name: direction

  atelier:
    build:
      context: ./user/atelier
      dockerfile: Dockerfile
    networks:
      local_network:
        ipv4_address: 192.168.0.104
    container_name: atelier

networks:
  local_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.254

  net_Secretariat:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1

  net_Compta:
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24
          gateway: 192.168.2.1

  net_Direction:
    ipam:
      driver: default
      config:
        - subnet: 192.168.3.0/24
          gateway: 192.168.3.1

  net_Atelier:
    ipam:
      driver: default
      config:
        - subnet: 192.168.4.0/24
          gateway: 192.168.4.1
