version: "3.3"

services:
  dns:
    build: ./SOA-externe/.
    ports:
      - 53:53/udp
      - 53:53/tcp
      - 953:953/udp
      - 953:953/tcp
    container_name: dns
    deploy:
     # If the container Exit docker try to restart it 20s after and retry each minute
     restart_policy:
       condition: any
       delay: 20s
       window: 60s
  
  web:
    build: ./Web-public/.
    ports:
      - 80:80
      - 443:443
    container_name: web
    deploy:
     restart_policy:
       condition: any
       delay: 20s
       window: 60s
  
  voip:
    build: ./VOIP/.
    ports:
      - 5060:5060
      - 19000-19250:19000-19250
    container_name: voip   
    deploy:
     resources:
       limits:
         memory: 400M
     restart_policy:
       condition: any
       delay: 20s
       window: 60s

  mail:
    build: ./Mail
    ports:
      - 25:25/tcp   # SMTP
      - 110:110/tcp # IMAP
      - 143:143/tcp # POP
    container_name: mail
    volumes:
      - ./Mail/postfix/main.cf:/etc/postfix/main.cf
      - ./Mail/dovecot/dovecot.conf:/etc/dovecot/dovecot.conf
    deploy:
      restart_policy:
        condition: any
        delay: 20s
        window: 60s
