version: "3.3"

secrets:
  root_password:
    file: ./database/root_password.txt
  website_password:
    file: ./database/website_password.txt

services:

  database:
    image: mysql:latest
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306/tcp
    secrets:
      - root_password
      - website_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/root_password
      MYSQL_USER: website
      MYSQL_PASSWORD_FILE: /run/secrets/website_password
    container_name: database

  resolver:
    build:
      context: ./ServicesInternes/resolver
      dockerfile: Dockerfile
    networks:
      local_network:
        ipv4_address: 192.168.0.5
    container_name: resolver

  soa_interne:
    build:
      context: ./ServicesInternes/soa_interne
      dockerfile: Dockerfile
    networks:
      local_network:
        ipv4_address: 192.168.0.6
    container_name: soa
    expose:
      - "53"

  intranet:
    build:
      context: ./ServicesInternes/intranet
      dockerfile: Dockerfile
    networks:
      local_network:
        ipv4_address: 192.168.0.3
    expose:
      - "80"
      - "443" 
    container_name: intranet

  samba:
    build:
      context: ./ServicesInternes/samba
      dockerfile: Dockerfile
    networks:
      local_network:
        ipv4_address: 192.168.0.4
    expose:
      - "139"
    container_name: samba

  secretariat:
    build:
      context: ./ServicesInternes/user/secretariat
      dockerfile: Dockerfile
    volumes:
      - ./ServicesInternes/user/resolv.conf:/etc/resolv.conf
    networks:
      local_network:
        ipv4_address: 192.168.0.101
    container_name: secretariat

  compta:
    build:
      context: ./ServicesInternes/user/compta
      dockerfile: Dockerfile
    volumes:
      - ./ServicesInternes/user/resolv.conf:/etc/resolv.conf
    networks:
      local_network:
        ipv4_address: 192.168.0.102
    container_name: compta

  direction:
    build:
      context: ./ServicesInternes/user/direction
      dockerfile: Dockerfile
    volumes:
      - ./ServicesInternes/user/resolv.conf:/etc/resolv.conf
    networks:
      local_network:
        ipv4_address: 192.168.0.103
    container_name: direction

  atelier:
    build:
      context: ./ServicesInternes/user/atelier
      dockerfile: Dockerfile
    volumes:
      - ./ServicesInternes/user/resolv.conf:/etc/resolv.conf
    networks:
      local_network:
        ipv4_address: 192.168.0.104
    container_name: atelier

networks:
  local_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24

  net_Secretariat:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24

  net_Compta:
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24

  net_Direction:
    ipam:
      driver: default
      config:
        - subnet: 192.168.3.0/24

  net_Atelier:
    ipam:
      driver: default
      config:
        - subnet: 192.168.4.0/24
